# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ProjectF02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Phone'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
  # Pods for ProjectF02

end
